
### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Karen",
  "email": "karen@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Session Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "aakash@test.com",
  "password": "password"
}


### Wager Create
POST http://localhost:3000/wagers.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODM3NzIxMjV9.VFQdSfWFO7DFOf4XXkK2jPqPsI1OzD1fflgy0sHsL5o

{
  "bet_type_id": 1,
  "sport_id": 1,
  "wager_amount": 5.00,
  "odds": -115,
  "win": false
}

### Wager Destroy
DELETE http://localhost:3000/wagers/9.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODM4Njc0NzB9.7_PE-GrqHymuk7Rii3Fd4SZeflNihk6XPayO2hqGE4o


### Odds API Sports Index
GET http://localhost:3000/odds.json
Content-Type: application/json